#!/bin/bash
for dir in `ls -ad /proc/{1..9}*`;
do
	# check to see if the smaps file is there and if the 'Swap' variable is in the file 
	# I wanted to check if the file was not empty but all smaps files show a size of 0
	if [ -f "$dir/smaps" -a -n "`grep -i swap $dir/smaps | head -1`" ]; then
		pid=`echo $dir | cut -d / -f3`
		process=`ps -p $pid -o comm --no-headers`
		echo -n "$process : "
		awk '/Swap/{sum+=$2}END{print sum}' $dir/smaps | column -t
	fi
done

# Show the total from all the processes running at the end.
echo -en "\nTotal : "
awk '/Swap/{sum+=$2}END{print sum}' /proc/*/smaps | column -t

## One Liner
# for dir in `ls -ad /proc/{1..9}*`; do if [ -f "$dir/smaps" -a -n "`grep -i swap $dir/smaps | head -1`" ]; then pid=`echo $dir | cut -d / -f3`; process=`ps -p $pid -o comm --no-headers`; echo -n "$process : "; awk '/Swap/{sum+=$2}END{print sum}' $dir/smaps | column -t; fi; done; echo -en "\nTotal : "; awk '/Swap/{sum+=$2}END{print sum}' /proc/*/smaps | column -t